version: '3.8'

services:
  app:
    image: ghcr.io/just111n/computer_vision_space_occupancy_project-web:latest  # Pull from GHCR
    container_name: flask_gunicorn_app
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:5000 app:app
